import sys

choice = int(sys.argv[1])

def print_choice_1():
  print('Time\tPID0\t\tCPU\tIO')
  print('----\t----\t\t---\t--')
  print('1\tRUN:CPU\t\t1')
  print('2\tRUN:CPU\t\t1')
  print('3\tRUN:CPU\t\t1')
  print('4\tRUN:CPU\t\t1')
  print('5\tRUN:CPU\t\t1')
  
def print_choice_2():
  print('Time\tPID0\t\tPID1\t\tCPU\tIO')
  print('----\t----\t\t----\t\t---\t--')
  print('1\tRUN:CPU\t\tREADY\t\t1')
  print('2\tRUN:CPU\t\tREADY\t\t1')
  print('3\tRUN:CPU\t\tREADY\t\t1')
  print('4\tRUN:CPU\t\tREADY\t\t1')
  print('5\tRUN:CPU\t\tREADY\t\t1')
  print('6\tDONE\t\tRUN:CPU\t\t1')
  print('7\tDONE\t\tRUN:CPU\t\t1')
  print('8\tDONE\t\tRUN:CPU\t\t1')
  print('9\tDONE\t\tRUN:CPU\t\t1')
  print('10\tDONE\t\tRUN:CPU\t\t1')
  
def print_choice_3():
  print('Time\tPID0\t\tCPU\tIO')
  print('----\t----\t\t---\t--')
  print('1\tRUN:IO\t\t1')
  print('2\tWAITING\t\t\t1')
  print('3\tWAITING\t\t\t1')
  print('4\tWAITING\t\t\t1')
  print('5\tWAITING\t\t\t1')
  print('6\tWAITING\t\t\t1')
  print('7\tRUN:IO DONE\t1')
  print('8\tRUN:IO\t\t1')
  print('9\tWAITING\t\t\t1')
  print('10\tWAITING\t\t\t1')
  print('11\tWAITING\t\t\t1')
  print('12\tWAITING\t\t\t1')
  print('13\tWAITING\t\t\t1')
  print('14\tRUN:IO DONE\t1')
  print('15\tRUN:IO\t\t1')
  print('16\tWAITING\t\t\t1')
  print('17\tWAITING\t\t\t1')
  print('18\tWAITING\t\t\t1')
  print('19\tWAITING\t\t\t1')
  print('20\tWAITING\t\t\t1')
  print('21\tRUN:IO DONE\t1')
  
def print_choice_4():
  print_choice_3()
  print('')
  print('Stats')
  print('-----')
  print('Total time: 21')
  print('CPU busy: 6 (25.57%)')
  print('IO busy: 15 (71.43%)')
  
def print_choice_5():
  print('Time\tPID0\t\tPID1\t\tCPU\tIO')
  print('----\t----\t\t----\t\t---\t--')
  print('1\tRUN:IO\t\tREADY\t\t1')
  print('2\tWAITING\t\tRUN:CPU\t\t1\t1')
  print('3\tWAITING\t\tRUN:CPU\t\t1\t1')
  print('4\tWAITING\t\tRUN:CPU\t\t1\t1')
  print('5\tWAITING\t\tDONE\t\t\t1')
  print('6\tWAITING\t\tDONE\t\t\t1')
  print('7\tRUN:IO DONE\tDONE\t\t1')
  print('8\tRUN:CPU\t\tDONE\t\t1')
  print('9\tRUN:CPU\t\tDONE\t\t1')
  print('')
  print('Stats')
  print('-----')
  print('Total time: 9')
  print('CPU busy: 7 (77.78%)')
  print('IO busy: 5 (55.56%)')

def print_choice_6():
  print('Think about what would happen when you run these processes:')
  print('PID0')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('')
  print('PID1')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('')
  print('''Remember:
  The system switches when the current process is DONE or issues an IO request.
  After an IO request, the process issuing the IO waits until it is its turn to run again.''')
  
def print_choice_7():
  print('Think about what would happen when you run these processes:')
  print('PID0')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('  CPU')
  print('')
  print('PID1')
  print('  IO')
  print('  IO DONE')
  print('')
  print('''Remember:
  The system switches when the current process is DONE or issues an IO request.
  After an IO request, the process issuing the IO waits until it is its turn to run again.''')
  
def print_choice_8():
  print('Time\tPID0\t\tPID1\t\tCPU\tIO')
  print('----\t----\t\t----\t\t---\t--')
  print('1\tCPU:IO\t\tREADY\t\t1')
  print('2\tWAITING\t\tREADY\t\t\t1')
  print('3\tWAITING\t\tREADY\t\t\t1')
  print('4\tWAITING\t\tREADY\t\t\t1')
  print('5\tWAITING\t\tREADY\t\t\t1')
  print('6\tWAITING\t\tREADY\t\t\t1')
  print('7\tCPU:IO DONE\tREADY\t\t1')
  print('8\tDONE\t\tCPU:RUN\t\t1')
  print('9\tDONE\t\tCPU:RUN\t\t1')
  print('10\tDONE\t\tCPU:RUN\t\t1')
  print('11\tDONE\t\tCPU:RUN\t\t1')

def print_choice_9():
  print('Time\tPID0\t\tPID1\t\tCPU\tIO')
  print('----\t----\t\t----\t\t---\t--')
  print('1\tRUN:IO\t\tREADY\t\t1')
  print('2\tWAITING\t\tRUN:CPU\t\t1\t1')
  print('3\tWAITING\t\tRUN:CPU\t\t1\t1')
  print('4\tWAITING\t\tRUN:CPU\t\t1\t1')
  print('5\tWAITING\t\tRUN:CPU\t\t1\t1')
  print('6\tWAITING\t\tDONE\t\t\t1')
  print('7\tRUN:IO DONE\tDONE\t\t1')
  
def print_choice_10():
  print('Time\tPID0\t\tPID1\t\tPID2\t\tPID3\t\tCPU\tIO')
  print('----\t----\t\t----\t\t----\t\t----\t\t---\t--')
  print('1\tRUN:IO\t\tREADY\t\tREADY\t\tREADY\t\t1\t')
  print('2\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('3\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('4\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('5\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('6\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('7\tREADY\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t')
  print('8\tREADY\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t')
  print('9\tREADY\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t')
  print('10\tREADY\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t')
  print('11\tREADY\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t')
  print('12\tREADY\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t')
  print('13\tREADY\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t')
  print('14\tREADY\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t')
  print('15\tREADY\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t')
  print('16\tREADY\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t')
  print('17\tRUN:IO DONE\tDONE\t\tDONE\t\tDONE\t\t1\t')
  print('18\tRUN:IO\t\tDONE\t\tDONE\t\tDONE\t\t1\t')
  print('19\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('20\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('21\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('22\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('23\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('24\tRUN:IO DONE\tDONE\t\tDONE\t\tDONE\t\t1')
  print('25\tRUN:IO\t\tDONE\t\tDONE\t\tDONE\t\t1')
  print('26\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('27\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('28\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('29\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('30\tWAITING\t\tDONE\t\tDONE\t\tDONE\t\t\t1')
  print('31\tRUN:IO DONE\tDONE\t\tDONE\t\tDONE\t\t1')
  print('')
  print('Stats')
  print('-----')
  print('Total time: 31')
  print('CPU busy: 21 (67.74%)')
  print('IO busy: 15 (48.39%)')

def print_choice_11():
  print('Time\tPID0\t\tPID1\t\tPID2\t\tPID3\t\tCPU\tIO')
  print('----\t----\t\t----\t\t----\t\t----\t\t---\t--')
  print('1\tRUN:IO\t\tREADY\t\tREADY\t\tREADY\t\t1\t')
  print('2\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('3\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('4\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('5\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('6\tWAITING\t\tRUN:CPU\t\tREADY\t\tREADY\t\t1\t1')
  print('7\tRUN:IO DONE\tDONE\t\tREADY\t\tREADY\t\t1\t')
  print('8\tRUN:IO\t\tDONE\t\tREADY\t\tREADY\t\t1\t')
  print('9\tWAITING\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t1')
  print('10\tWAITING\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t1')
  print('11\tWAITING\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t1')
  print('12\tWAITING\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t1')
  print('13\tWAITING\t\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t1')
  print('14\tRUN:IO DONE\tDONE\t\tRUN:CPU\t\tREADY\t\t1\t')
  print('15\tRUN:IO\t\tDONE\t\tDONE\t\tREADY\t\t1\t')
  print('16\tWAITING\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t1')
  print('17\tWAITING\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t1')
  print('18\tWAITING\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t1')
  print('19\tWAITING\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t1')
  print('20\tWAITING\t\tDONE\t\tDONE\t\tRUN:CPU\t\t1\t1')
  print('21\tRUN:IO DONE\tDONE\t\tDONE\t\tDONE\t\t1\t')
  print('')
  print('Stats')
  print('-----')
  print('Total time: 21')
  print('CPU busy: 21 (100%)')
  print('IO busy: 15 (71.43%)')

if choice == 1:
  print_choice_1()
elif choice == 2:
  print_choice_2()
elif choice == 3:
  print_choice_3()
elif choice == 4:
  print_choice_4()
elif choice == 5:
  print_choice_5()
elif choice == 6:
  print_choice_6()
elif choice == 7:
  print_choice_7()
elif choice == 8:
  print_choice_8()
elif choice == 9:
  print_choice_9()
elif choice == 10:
  print_choice_10()
elif choice == 11:
  print_choice_11()
  
print('')